// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbwkhqvrqhagoswehrkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRid2tocXZycWhhZ29zd2Vocmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4MDQ3NDMsImV4cCI6MjA3OTM4MDc0M30.GkJN4dDbGbrViG45ThdlNNGjuobiRaEotiSp--rppzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});